// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// compute_ind_matrix_cpp
arma::mat compute_ind_matrix_cpp(const arma::mat& factor_expr_norm, const arma::mat& factor_expr_raw, const arma::mat& gene_expr_norm, const arma::sp_mat& W, double quantile_prob, int min_cells);
RcppExport SEXP _sigdiscov_compute_ind_matrix_cpp(SEXP factor_expr_normSEXP, SEXP factor_expr_rawSEXP, SEXP gene_expr_normSEXP, SEXP WSEXP, SEXP quantile_probSEXP, SEXP min_cellsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type factor_expr_norm(factor_expr_normSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type factor_expr_raw(factor_expr_rawSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type gene_expr_norm(gene_expr_normSEXP);
    Rcpp::traits::input_parameter< const arma::sp_mat& >::type W(WSEXP);
    Rcpp::traits::input_parameter< double >::type quantile_prob(quantile_probSEXP);
    Rcpp::traits::input_parameter< int >::type min_cells(min_cellsSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_ind_matrix_cpp(factor_expr_norm, factor_expr_raw, gene_expr_norm, W, quantile_prob, min_cells));
    return rcpp_result_gen;
END_RCPP
}
// batch_compute_all_pairs_cpp
List batch_compute_all_pairs_cpp(const arma::mat& expr_matrix, const arma::mat& coords, const std::vector<std::string>& cell_types, const arma::uvec& factor_indices, const arma::vec& radii, const DataFrame& pairs, double quantile_prob, int min_cells, int min_connections, bool verbose);
RcppExport SEXP _sigdiscov_batch_compute_all_pairs_cpp(SEXP expr_matrixSEXP, SEXP coordsSEXP, SEXP cell_typesSEXP, SEXP factor_indicesSEXP, SEXP radiiSEXP, SEXP pairsSEXP, SEXP quantile_probSEXP, SEXP min_cellsSEXP, SEXP min_connectionsSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type expr_matrix(expr_matrixSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type coords(coordsSEXP);
    Rcpp::traits::input_parameter< const std::vector<std::string>& >::type cell_types(cell_typesSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type factor_indices(factor_indicesSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type radii(radiiSEXP);
    Rcpp::traits::input_parameter< const DataFrame& >::type pairs(pairsSEXP);
    Rcpp::traits::input_parameter< double >::type quantile_prob(quantile_probSEXP);
    Rcpp::traits::input_parameter< int >::type min_cells(min_cellsSEXP);
    Rcpp::traits::input_parameter< int >::type min_connections(min_connectionsSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(batch_compute_all_pairs_cpp(expr_matrix, coords, cell_types, factor_indices, radii, pairs, quantile_prob, min_cells, min_connections, verbose));
    return rcpp_result_gen;
END_RCPP
}
// compute_moran_from_lag_cpp
double compute_moran_from_lag_cpp(const arma::vec& z_f, const arma::vec& lag_g);
RcppExport SEXP _sigdiscov_compute_moran_from_lag_cpp(SEXP z_fSEXP, SEXP lag_gSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type z_f(z_fSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type lag_g(lag_gSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_moran_from_lag_cpp(z_f, lag_g));
    return rcpp_result_gen;
END_RCPP
}
// compute_ind_from_lag_cpp
double compute_ind_from_lag_cpp(const arma::vec& z_f, const arma::vec& lag_g);
RcppExport SEXP _sigdiscov_compute_ind_from_lag_cpp(SEXP z_fSEXP, SEXP lag_gSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type z_f(z_fSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type lag_g(lag_gSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_ind_from_lag_cpp(z_f, lag_g));
    return rcpp_result_gen;
END_RCPP
}
// compute_metric_batch_cpp
arma::vec compute_metric_batch_cpp(const arma::vec& z_f, const arma::mat& lag_G, const std::string& metric);
RcppExport SEXP _sigdiscov_compute_metric_batch_cpp(SEXP z_fSEXP, SEXP lag_GSEXP, SEXP metricSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type z_f(z_fSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type lag_G(lag_GSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type metric(metricSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_metric_batch_cpp(z_f, lag_G, metric));
    return rcpp_result_gen;
END_RCPP
}
// standardize_vec_cpp
arma::vec standardize_vec_cpp(const arma::vec& x);
RcppExport SEXP _sigdiscov_standardize_vec_cpp(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(standardize_vec_cpp(x));
    return rcpp_result_gen;
END_RCPP
}
// standardize_matrix_cpp
arma::mat standardize_matrix_cpp(const arma::mat& X);
RcppExport SEXP _sigdiscov_standardize_matrix_cpp(SEXP XSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    rcpp_result_gen = Rcpp::wrap(standardize_matrix_cpp(X));
    return rcpp_result_gen;
END_RCPP
}
// cpp_create_distance
NumericMatrix cpp_create_distance(int max_shift, int mode);
RcppExport SEXP _sigdiscov_cpp_create_distance(SEXP max_shiftSEXP, SEXP modeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type max_shift(max_shiftSEXP);
    Rcpp::traits::input_parameter< int >::type mode(modeSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_create_distance(max_shift, mode));
    return rcpp_result_gen;
END_RCPP
}
// cpp_z_normalize
arma::mat cpp_z_normalize(arma::mat data);
RcppExport SEXP _sigdiscov_cpp_z_normalize(SEXP dataSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type data(dataSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_z_normalize(data));
    return rcpp_result_gen;
END_RCPP
}
// cpp_create_weight_matrix
List cpp_create_weight_matrix(IntegerVector spot_row, IntegerVector spot_col, NumericMatrix distance, int max_shift, bool flag_samespot);
RcppExport SEXP _sigdiscov_cpp_create_weight_matrix(SEXP spot_rowSEXP, SEXP spot_colSEXP, SEXP distanceSEXP, SEXP max_shiftSEXP, SEXP flag_samespotSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type spot_row(spot_rowSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type spot_col(spot_colSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type distance(distanceSEXP);
    Rcpp::traits::input_parameter< int >::type max_shift(max_shiftSEXP);
    Rcpp::traits::input_parameter< bool >::type flag_samespot(flag_samespotSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_create_weight_matrix(spot_row, spot_col, distance, max_shift, flag_samespot));
    return rcpp_result_gen;
END_RCPP
}
// cpp_pairwise_moran
arma::mat cpp_pairwise_moran(arma::mat data, arma::mat W, double weight_sum, bool paired_genes, bool all_genes);
RcppExport SEXP _sigdiscov_cpp_pairwise_moran(SEXP dataSEXP, SEXP WSEXP, SEXP weight_sumSEXP, SEXP paired_genesSEXP, SEXP all_genesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type data(dataSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type W(WSEXP);
    Rcpp::traits::input_parameter< double >::type weight_sum(weight_sumSEXP);
    Rcpp::traits::input_parameter< bool >::type paired_genes(paired_genesSEXP);
    Rcpp::traits::input_parameter< bool >::type all_genes(all_genesSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_pairwise_moran(data, W, weight_sum, paired_genes, all_genes));
    return rcpp_result_gen;
END_RCPP
}
// cpp_pairwise_moran_sparse
arma::mat cpp_pairwise_moran_sparse(arma::sp_mat data_sparse, arma::mat W, double weight_sum, bool paired_genes, bool all_genes);
RcppExport SEXP _sigdiscov_cpp_pairwise_moran_sparse(SEXP data_sparseSEXP, SEXP WSEXP, SEXP weight_sumSEXP, SEXP paired_genesSEXP, SEXP all_genesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::sp_mat >::type data_sparse(data_sparseSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type W(WSEXP);
    Rcpp::traits::input_parameter< double >::type weight_sum(weight_sumSEXP);
    Rcpp::traits::input_parameter< bool >::type paired_genes(paired_genesSEXP);
    Rcpp::traits::input_parameter< bool >::type all_genes(all_genesSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_pairwise_moran_sparse(data_sparse, W, weight_sum, paired_genes, all_genes));
    return rcpp_result_gen;
END_RCPP
}
// cpp_compute_moran_full
arma::mat cpp_compute_moran_full(arma::mat data, IntegerVector spot_row, IntegerVector spot_col, int max_radius, int platform, bool flag_samespot, bool paired_genes, bool all_genes, bool verbose);
RcppExport SEXP _sigdiscov_cpp_compute_moran_full(SEXP dataSEXP, SEXP spot_rowSEXP, SEXP spot_colSEXP, SEXP max_radiusSEXP, SEXP platformSEXP, SEXP flag_samespotSEXP, SEXP paired_genesSEXP, SEXP all_genesSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type data(dataSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type spot_row(spot_rowSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type spot_col(spot_colSEXP);
    Rcpp::traits::input_parameter< int >::type max_radius(max_radiusSEXP);
    Rcpp::traits::input_parameter< int >::type platform(platformSEXP);
    Rcpp::traits::input_parameter< bool >::type flag_samespot(flag_samespotSEXP);
    Rcpp::traits::input_parameter< bool >::type paired_genes(paired_genesSEXP);
    Rcpp::traits::input_parameter< bool >::type all_genes(all_genesSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_compute_moran_full(data, spot_row, spot_col, max_radius, platform, flag_samespot, paired_genes, all_genes, verbose));
    return rcpp_result_gen;
END_RCPP
}
// cpp_compute_moran_full_sparse
arma::mat cpp_compute_moran_full_sparse(arma::sp_mat data_sparse, IntegerVector spot_row, IntegerVector spot_col, int max_radius, int platform, bool flag_samespot, bool paired_genes, bool all_genes, bool verbose);
RcppExport SEXP _sigdiscov_cpp_compute_moran_full_sparse(SEXP data_sparseSEXP, SEXP spot_rowSEXP, SEXP spot_colSEXP, SEXP max_radiusSEXP, SEXP platformSEXP, SEXP flag_samespotSEXP, SEXP paired_genesSEXP, SEXP all_genesSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::sp_mat >::type data_sparse(data_sparseSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type spot_row(spot_rowSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type spot_col(spot_colSEXP);
    Rcpp::traits::input_parameter< int >::type max_radius(max_radiusSEXP);
    Rcpp::traits::input_parameter< int >::type platform(platformSEXP);
    Rcpp::traits::input_parameter< bool >::type flag_samespot(flag_samespotSEXP);
    Rcpp::traits::input_parameter< bool >::type paired_genes(paired_genesSEXP);
    Rcpp::traits::input_parameter< bool >::type all_genes(all_genesSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_compute_moran_full_sparse(data_sparse, spot_row, spot_col, max_radius, platform, flag_samespot, paired_genes, all_genes, verbose));
    return rcpp_result_gen;
END_RCPP
}
// cpp_create_weight_matrix_sparse
List cpp_create_weight_matrix_sparse(IntegerVector spot_row, IntegerVector spot_col, NumericMatrix distance, int max_shift, bool flag_samespot);
RcppExport SEXP _sigdiscov_cpp_create_weight_matrix_sparse(SEXP spot_rowSEXP, SEXP spot_colSEXP, SEXP distanceSEXP, SEXP max_shiftSEXP, SEXP flag_samespotSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type spot_row(spot_rowSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type spot_col(spot_colSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type distance(distanceSEXP);
    Rcpp::traits::input_parameter< int >::type max_shift(max_shiftSEXP);
    Rcpp::traits::input_parameter< bool >::type flag_samespot(flag_samespotSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_create_weight_matrix_sparse(spot_row, spot_col, distance, max_shift, flag_samespot));
    return rcpp_result_gen;
END_RCPP
}
// cpp_pairwise_moran_W_sparse
arma::mat cpp_pairwise_moran_W_sparse(arma::mat data, arma::sp_mat W, double weight_sum, bool paired_genes, bool all_genes);
RcppExport SEXP _sigdiscov_cpp_pairwise_moran_W_sparse(SEXP dataSEXP, SEXP WSEXP, SEXP weight_sumSEXP, SEXP paired_genesSEXP, SEXP all_genesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type data(dataSEXP);
    Rcpp::traits::input_parameter< arma::sp_mat >::type W(WSEXP);
    Rcpp::traits::input_parameter< double >::type weight_sum(weight_sumSEXP);
    Rcpp::traits::input_parameter< bool >::type paired_genes(paired_genesSEXP);
    Rcpp::traits::input_parameter< bool >::type all_genes(all_genesSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_pairwise_moran_W_sparse(data, W, weight_sum, paired_genes, all_genes));
    return rcpp_result_gen;
END_RCPP
}
// cpp_compute_moran_full_W_sparse
arma::mat cpp_compute_moran_full_W_sparse(arma::mat data, IntegerVector spot_row, IntegerVector spot_col, int max_radius, int platform, bool flag_samespot, bool paired_genes, bool all_genes, bool verbose);
RcppExport SEXP _sigdiscov_cpp_compute_moran_full_W_sparse(SEXP dataSEXP, SEXP spot_rowSEXP, SEXP spot_colSEXP, SEXP max_radiusSEXP, SEXP platformSEXP, SEXP flag_samespotSEXP, SEXP paired_genesSEXP, SEXP all_genesSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type data(dataSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type spot_row(spot_rowSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type spot_col(spot_colSEXP);
    Rcpp::traits::input_parameter< int >::type max_radius(max_radiusSEXP);
    Rcpp::traits::input_parameter< int >::type platform(platformSEXP);
    Rcpp::traits::input_parameter< bool >::type flag_samespot(flag_samespotSEXP);
    Rcpp::traits::input_parameter< bool >::type paired_genes(paired_genesSEXP);
    Rcpp::traits::input_parameter< bool >::type all_genes(all_genesSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_compute_moran_full_W_sparse(data, spot_row, spot_col, max_radius, platform, flag_samespot, paired_genes, all_genes, verbose));
    return rcpp_result_gen;
END_RCPP
}
// permutation_test_cpp
List permutation_test_cpp(const arma::vec& z_f, const arma::vec& lag_g, const std::string& metric, int n_perm);
RcppExport SEXP _sigdiscov_permutation_test_cpp(SEXP z_fSEXP, SEXP lag_gSEXP, SEXP metricSEXP, SEXP n_permSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type z_f(z_fSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type lag_g(lag_gSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type metric(metricSEXP);
    Rcpp::traits::input_parameter< int >::type n_perm(n_permSEXP);
    rcpp_result_gen = Rcpp::wrap(permutation_test_cpp(z_f, lag_g, metric, n_perm));
    return rcpp_result_gen;
END_RCPP
}
// batch_permutation_test_cpp
DataFrame batch_permutation_test_cpp(const arma::vec& z_f, const arma::mat& Z_g, const arma::sp_mat& W, const std::string& metric, int n_perm);
RcppExport SEXP _sigdiscov_batch_permutation_test_cpp(SEXP z_fSEXP, SEXP Z_gSEXP, SEXP WSEXP, SEXP metricSEXP, SEXP n_permSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type z_f(z_fSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Z_g(Z_gSEXP);
    Rcpp::traits::input_parameter< const arma::sp_mat& >::type W(WSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type metric(metricSEXP);
    Rcpp::traits::input_parameter< int >::type n_perm(n_permSEXP);
    rcpp_result_gen = Rcpp::wrap(batch_permutation_test_cpp(z_f, Z_g, W, metric, n_perm));
    return rcpp_result_gen;
END_RCPP
}
// sparse_row_normalize_cpp
arma::sp_mat sparse_row_normalize_cpp(const arma::sp_mat& W);
RcppExport SEXP _sigdiscov_sparse_row_normalize_cpp(SEXP WSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::sp_mat& >::type W(WSEXP);
    rcpp_result_gen = Rcpp::wrap(sparse_row_normalize_cpp(W));
    return rcpp_result_gen;
END_RCPP
}
// create_gaussian_weights_cpp
arma::sp_mat create_gaussian_weights_cpp(const arma::mat& sender_coords, const arma::mat& receiver_coords, double radius, double inner_radius, double sigma, double min_weight);
RcppExport SEXP _sigdiscov_create_gaussian_weights_cpp(SEXP sender_coordsSEXP, SEXP receiver_coordsSEXP, SEXP radiusSEXP, SEXP inner_radiusSEXP, SEXP sigmaSEXP, SEXP min_weightSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type sender_coords(sender_coordsSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type receiver_coords(receiver_coordsSEXP);
    Rcpp::traits::input_parameter< double >::type radius(radiusSEXP);
    Rcpp::traits::input_parameter< double >::type inner_radius(inner_radiusSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< double >::type min_weight(min_weightSEXP);
    rcpp_result_gen = Rcpp::wrap(create_gaussian_weights_cpp(sender_coords, receiver_coords, radius, inner_radius, sigma, min_weight));
    return rcpp_result_gen;
END_RCPP
}
// create_gaussian_ring_weights_cpp
arma::sp_mat create_gaussian_ring_weights_cpp(const arma::mat& coords, double outer_radius, double inner_radius, double sigma);
RcppExport SEXP _sigdiscov_create_gaussian_ring_weights_cpp(SEXP coordsSEXP, SEXP outer_radiusSEXP, SEXP inner_radiusSEXP, SEXP sigmaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type coords(coordsSEXP);
    Rcpp::traits::input_parameter< double >::type outer_radius(outer_radiusSEXP);
    Rcpp::traits::input_parameter< double >::type inner_radius(inner_radiusSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    rcpp_result_gen = Rcpp::wrap(create_gaussian_ring_weights_cpp(coords, outer_radius, inner_radius, sigma));
    return rcpp_result_gen;
END_RCPP
}
// create_binary_weights_cpp
arma::sp_mat create_binary_weights_cpp(const arma::mat& coords, double radius, bool include_self);
RcppExport SEXP _sigdiscov_create_binary_weights_cpp(SEXP coordsSEXP, SEXP radiusSEXP, SEXP include_selfSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type coords(coordsSEXP);
    Rcpp::traits::input_parameter< double >::type radius(radiusSEXP);
    Rcpp::traits::input_parameter< bool >::type include_self(include_selfSEXP);
    rcpp_result_gen = Rcpp::wrap(create_binary_weights_cpp(coords, radius, include_self));
    return rcpp_result_gen;
END_RCPP
}
// create_ring_weights_cpp
arma::sp_mat create_ring_weights_cpp(const arma::mat& coords, double inner_radius, double outer_radius);
RcppExport SEXP _sigdiscov_create_ring_weights_cpp(SEXP coordsSEXP, SEXP inner_radiusSEXP, SEXP outer_radiusSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type coords(coordsSEXP);
    Rcpp::traits::input_parameter< double >::type inner_radius(inner_radiusSEXP);
    Rcpp::traits::input_parameter< double >::type outer_radius(outer_radiusSEXP);
    rcpp_result_gen = Rcpp::wrap(create_ring_weights_cpp(coords, inner_radius, outer_radius));
    return rcpp_result_gen;
END_RCPP
}
// create_directional_weights_cpp
arma::sp_mat create_directional_weights_cpp(const arma::mat& sender_coords, const arma::mat& receiver_coords, double radius);
RcppExport SEXP _sigdiscov_create_directional_weights_cpp(SEXP sender_coordsSEXP, SEXP receiver_coordsSEXP, SEXP radiusSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type sender_coords(sender_coordsSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type receiver_coords(receiver_coordsSEXP);
    Rcpp::traits::input_parameter< double >::type radius(radiusSEXP);
    rcpp_result_gen = Rcpp::wrap(create_directional_weights_cpp(sender_coords, receiver_coords, radius));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_sigdiscov_compute_ind_matrix_cpp", (DL_FUNC) &_sigdiscov_compute_ind_matrix_cpp, 6},
    {"_sigdiscov_batch_compute_all_pairs_cpp", (DL_FUNC) &_sigdiscov_batch_compute_all_pairs_cpp, 10},
    {"_sigdiscov_compute_moran_from_lag_cpp", (DL_FUNC) &_sigdiscov_compute_moran_from_lag_cpp, 2},
    {"_sigdiscov_compute_ind_from_lag_cpp", (DL_FUNC) &_sigdiscov_compute_ind_from_lag_cpp, 2},
    {"_sigdiscov_compute_metric_batch_cpp", (DL_FUNC) &_sigdiscov_compute_metric_batch_cpp, 3},
    {"_sigdiscov_standardize_vec_cpp", (DL_FUNC) &_sigdiscov_standardize_vec_cpp, 1},
    {"_sigdiscov_standardize_matrix_cpp", (DL_FUNC) &_sigdiscov_standardize_matrix_cpp, 1},
    {"_sigdiscov_cpp_create_distance", (DL_FUNC) &_sigdiscov_cpp_create_distance, 2},
    {"_sigdiscov_cpp_z_normalize", (DL_FUNC) &_sigdiscov_cpp_z_normalize, 1},
    {"_sigdiscov_cpp_create_weight_matrix", (DL_FUNC) &_sigdiscov_cpp_create_weight_matrix, 5},
    {"_sigdiscov_cpp_pairwise_moran", (DL_FUNC) &_sigdiscov_cpp_pairwise_moran, 5},
    {"_sigdiscov_cpp_pairwise_moran_sparse", (DL_FUNC) &_sigdiscov_cpp_pairwise_moran_sparse, 5},
    {"_sigdiscov_cpp_compute_moran_full", (DL_FUNC) &_sigdiscov_cpp_compute_moran_full, 9},
    {"_sigdiscov_cpp_compute_moran_full_sparse", (DL_FUNC) &_sigdiscov_cpp_compute_moran_full_sparse, 9},
    {"_sigdiscov_cpp_create_weight_matrix_sparse", (DL_FUNC) &_sigdiscov_cpp_create_weight_matrix_sparse, 5},
    {"_sigdiscov_cpp_pairwise_moran_W_sparse", (DL_FUNC) &_sigdiscov_cpp_pairwise_moran_W_sparse, 5},
    {"_sigdiscov_cpp_compute_moran_full_W_sparse", (DL_FUNC) &_sigdiscov_cpp_compute_moran_full_W_sparse, 9},
    {"_sigdiscov_permutation_test_cpp", (DL_FUNC) &_sigdiscov_permutation_test_cpp, 4},
    {"_sigdiscov_batch_permutation_test_cpp", (DL_FUNC) &_sigdiscov_batch_permutation_test_cpp, 5},
    {"_sigdiscov_sparse_row_normalize_cpp", (DL_FUNC) &_sigdiscov_sparse_row_normalize_cpp, 1},
    {"_sigdiscov_create_gaussian_weights_cpp", (DL_FUNC) &_sigdiscov_create_gaussian_weights_cpp, 6},
    {"_sigdiscov_create_gaussian_ring_weights_cpp", (DL_FUNC) &_sigdiscov_create_gaussian_ring_weights_cpp, 4},
    {"_sigdiscov_create_binary_weights_cpp", (DL_FUNC) &_sigdiscov_create_binary_weights_cpp, 3},
    {"_sigdiscov_create_ring_weights_cpp", (DL_FUNC) &_sigdiscov_create_ring_weights_cpp, 3},
    {"_sigdiscov_create_directional_weights_cpp", (DL_FUNC) &_sigdiscov_create_directional_weights_cpp, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_sigdiscov(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
