// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// cpp_create_distance
NumericMatrix cpp_create_distance(int max_shift, int mode);
RcppExport SEXP _sigdiscov_cpp_create_distance(SEXP max_shiftSEXP, SEXP modeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type max_shift(max_shiftSEXP);
    Rcpp::traits::input_parameter< int >::type mode(modeSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_create_distance(max_shift, mode));
    return rcpp_result_gen;
END_RCPP
}
// cpp_z_normalize
arma::mat cpp_z_normalize(arma::mat data);
RcppExport SEXP _sigdiscov_cpp_z_normalize(SEXP dataSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type data(dataSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_z_normalize(data));
    return rcpp_result_gen;
END_RCPP
}
// cpp_create_weight_matrix
List cpp_create_weight_matrix(IntegerVector spot_row, IntegerVector spot_col, NumericMatrix distance, int max_shift, bool flag_samespot);
RcppExport SEXP _sigdiscov_cpp_create_weight_matrix(SEXP spot_rowSEXP, SEXP spot_colSEXP, SEXP distanceSEXP, SEXP max_shiftSEXP, SEXP flag_samespotSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type spot_row(spot_rowSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type spot_col(spot_colSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type distance(distanceSEXP);
    Rcpp::traits::input_parameter< int >::type max_shift(max_shiftSEXP);
    Rcpp::traits::input_parameter< bool >::type flag_samespot(flag_samespotSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_create_weight_matrix(spot_row, spot_col, distance, max_shift, flag_samespot));
    return rcpp_result_gen;
END_RCPP
}
// cpp_pairwise_moran
arma::mat cpp_pairwise_moran(arma::mat data, arma::mat W, double weight_sum, bool paired_genes, bool all_genes);
RcppExport SEXP _sigdiscov_cpp_pairwise_moran(SEXP dataSEXP, SEXP WSEXP, SEXP weight_sumSEXP, SEXP paired_genesSEXP, SEXP all_genesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type data(dataSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type W(WSEXP);
    Rcpp::traits::input_parameter< double >::type weight_sum(weight_sumSEXP);
    Rcpp::traits::input_parameter< bool >::type paired_genes(paired_genesSEXP);
    Rcpp::traits::input_parameter< bool >::type all_genes(all_genesSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_pairwise_moran(data, W, weight_sum, paired_genes, all_genes));
    return rcpp_result_gen;
END_RCPP
}
// cpp_pairwise_moran_sparse
arma::mat cpp_pairwise_moran_sparse(arma::sp_mat data_sparse, arma::mat W, double weight_sum, bool paired_genes, bool all_genes);
RcppExport SEXP _sigdiscov_cpp_pairwise_moran_sparse(SEXP data_sparseSEXP, SEXP WSEXP, SEXP weight_sumSEXP, SEXP paired_genesSEXP, SEXP all_genesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::sp_mat >::type data_sparse(data_sparseSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type W(WSEXP);
    Rcpp::traits::input_parameter< double >::type weight_sum(weight_sumSEXP);
    Rcpp::traits::input_parameter< bool >::type paired_genes(paired_genesSEXP);
    Rcpp::traits::input_parameter< bool >::type all_genes(all_genesSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_pairwise_moran_sparse(data_sparse, W, weight_sum, paired_genes, all_genes));
    return rcpp_result_gen;
END_RCPP
}
// cpp_compute_moran_full
arma::mat cpp_compute_moran_full(arma::mat data, IntegerVector spot_row, IntegerVector spot_col, int max_radius, int platform, bool flag_samespot, bool paired_genes, bool all_genes, bool verbose);
RcppExport SEXP _sigdiscov_cpp_compute_moran_full(SEXP dataSEXP, SEXP spot_rowSEXP, SEXP spot_colSEXP, SEXP max_radiusSEXP, SEXP platformSEXP, SEXP flag_samespotSEXP, SEXP paired_genesSEXP, SEXP all_genesSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type data(dataSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type spot_row(spot_rowSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type spot_col(spot_colSEXP);
    Rcpp::traits::input_parameter< int >::type max_radius(max_radiusSEXP);
    Rcpp::traits::input_parameter< int >::type platform(platformSEXP);
    Rcpp::traits::input_parameter< bool >::type flag_samespot(flag_samespotSEXP);
    Rcpp::traits::input_parameter< bool >::type paired_genes(paired_genesSEXP);
    Rcpp::traits::input_parameter< bool >::type all_genes(all_genesSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_compute_moran_full(data, spot_row, spot_col, max_radius, platform, flag_samespot, paired_genes, all_genes, verbose));
    return rcpp_result_gen;
END_RCPP
}
// cpp_compute_moran_full_sparse
arma::mat cpp_compute_moran_full_sparse(arma::sp_mat data_sparse, IntegerVector spot_row, IntegerVector spot_col, int max_radius, int platform, bool flag_samespot, bool paired_genes, bool all_genes, bool verbose);
RcppExport SEXP _sigdiscov_cpp_compute_moran_full_sparse(SEXP data_sparseSEXP, SEXP spot_rowSEXP, SEXP spot_colSEXP, SEXP max_radiusSEXP, SEXP platformSEXP, SEXP flag_samespotSEXP, SEXP paired_genesSEXP, SEXP all_genesSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::sp_mat >::type data_sparse(data_sparseSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type spot_row(spot_rowSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type spot_col(spot_colSEXP);
    Rcpp::traits::input_parameter< int >::type max_radius(max_radiusSEXP);
    Rcpp::traits::input_parameter< int >::type platform(platformSEXP);
    Rcpp::traits::input_parameter< bool >::type flag_samespot(flag_samespotSEXP);
    Rcpp::traits::input_parameter< bool >::type paired_genes(paired_genesSEXP);
    Rcpp::traits::input_parameter< bool >::type all_genes(all_genesSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_compute_moran_full_sparse(data_sparse, spot_row, spot_col, max_radius, platform, flag_samespot, paired_genes, all_genes, verbose));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_sigdiscov_cpp_create_distance", (DL_FUNC) &_sigdiscov_cpp_create_distance, 2},
    {"_sigdiscov_cpp_z_normalize", (DL_FUNC) &_sigdiscov_cpp_z_normalize, 1},
    {"_sigdiscov_cpp_create_weight_matrix", (DL_FUNC) &_sigdiscov_cpp_create_weight_matrix, 5},
    {"_sigdiscov_cpp_pairwise_moran", (DL_FUNC) &_sigdiscov_cpp_pairwise_moran, 5},
    {"_sigdiscov_cpp_pairwise_moran_sparse", (DL_FUNC) &_sigdiscov_cpp_pairwise_moran_sparse, 5},
    {"_sigdiscov_cpp_compute_moran_full", (DL_FUNC) &_sigdiscov_cpp_compute_moran_full, 9},
    {"_sigdiscov_cpp_compute_moran_full_sparse", (DL_FUNC) &_sigdiscov_cpp_compute_moran_full_sparse, 9},
    {NULL, NULL, 0}
};

RcppExport void R_init_sigdiscov(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
