# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_create_distance <- function(max_shift, mode) {
    .Call(`_sigdiscov_cpp_create_distance`, max_shift, mode)
}

cpp_z_normalize <- function(data) {
    .Call(`_sigdiscov_cpp_z_normalize`, data)
}

cpp_create_weight_matrix <- function(spot_row, spot_col, distance, max_shift, flag_samespot) {
    .Call(`_sigdiscov_cpp_create_weight_matrix`, spot_row, spot_col, distance, max_shift, flag_samespot)
}

cpp_pairwise_moran <- function(data, W, weight_sum, paired_genes = TRUE, all_genes = TRUE) {
    .Call(`_sigdiscov_cpp_pairwise_moran`, data, W, weight_sum, paired_genes, all_genes)
}

cpp_pairwise_moran_sparse <- function(data_sparse, W, weight_sum, paired_genes = TRUE, all_genes = TRUE) {
    .Call(`_sigdiscov_cpp_pairwise_moran_sparse`, data_sparse, W, weight_sum, paired_genes, all_genes)
}

cpp_compute_moran_full <- function(data, spot_row, spot_col, max_radius = 5L, platform = 0L, flag_samespot = TRUE, paired_genes = TRUE, all_genes = TRUE, verbose = TRUE) {
    .Call(`_sigdiscov_cpp_compute_moran_full`, data, spot_row, spot_col, max_radius, platform, flag_samespot, paired_genes, all_genes, verbose)
}

cpp_compute_moran_full_sparse <- function(data_sparse, spot_row, spot_col, max_radius = 5L, platform = 0L, flag_samespot = TRUE, paired_genes = TRUE, all_genes = TRUE, verbose = TRUE) {
    .Call(`_sigdiscov_cpp_compute_moran_full_sparse`, data_sparse, spot_row, spot_col, max_radius, platform, flag_samespot, paired_genes, all_genes, verbose)
}

cpp_create_ring_weight_matrix <- function(coords, r_inner, r_outer, sender_idx, receiver_idx, mode = 0L, row_normalize = TRUE) {
    .Call(`_sigdiscov_cpp_create_ring_weight_matrix`, coords, r_inner, r_outer, sender_idx, receiver_idx, mode, row_normalize)
}

cpp_compute_spatial_correlation <- function(z_f, z_g, W, mode = 0L) {
    .Call(`_sigdiscov_cpp_compute_spatial_correlation`, z_f, z_g, W, mode)
}

cpp_savgol_smooth <- function(y, window_size = 5L, poly_order = 2L) {
    .Call(`_sigdiscov_cpp_savgol_smooth`, y, window_size, poly_order)
}

cpp_compute_signed_delta_I <- function(I_smooth, radii) {
    .Call(`_sigdiscov_cpp_compute_signed_delta_I`, I_smooth, radii)
}

cpp_compute_moran_curve <- function(factor_expr, gene_expr, coords, radii, mode = 0L, sender_idx, receiver_idx) {
    .Call(`_sigdiscov_cpp_compute_moran_curve`, factor_expr, gene_expr, coords, radii, mode, sender_idx, receiver_idx)
}

cpp_define_sender_receiver <- function(factor_expr, percentile = 75.0) {
    .Call(`_sigdiscov_cpp_define_sender_receiver`, factor_expr, percentile)
}

cpp_compute_single_signature <- function(factor_expr, gene_expr, coords, radii, mode = 0L, sender_percentile = 75.0, smooth_window = 5L, smooth_poly = 2L) {
    .Call(`_sigdiscov_cpp_compute_single_signature`, factor_expr, gene_expr, coords, radii, mode, sender_percentile, smooth_window, smooth_poly)
}

cpp_precompute_ring_weights <- function(coords, radii, mode = 0L, sender_idx, receiver_idx) {
    .Call(`_sigdiscov_cpp_precompute_ring_weights`, coords, radii, mode, sender_idx, receiver_idx)
}

cpp_compute_all_signatures <- function(expr_matrix, gene_names, factor_idx, coords, radii, mode = 0L, sender_percentile = 75.0, smooth_window = 5L, smooth_poly = 2L, verbose = TRUE) {
    .Call(`_sigdiscov_cpp_compute_all_signatures`, expr_matrix, gene_names, factor_idx, coords, radii, mode, sender_percentile, smooth_window, smooth_poly, verbose)
}

cpp_compute_delta_I_matrix <- function(expr_matrix, coords, radii, smooth_window = 5L, smooth_poly = 2L, verbose = TRUE) {
    .Call(`_sigdiscov_cpp_compute_delta_I_matrix`, expr_matrix, coords, radii, smooth_window, smooth_poly, verbose)
}

cpp_compute_delta_I_matrix_chunked <- function(expr_matrix, coords, radii, chunk_size = 1000L, smooth_window = 5L, smooth_poly = 2L, verbose = TRUE) {
    .Call(`_sigdiscov_cpp_compute_delta_I_matrix_chunked`, expr_matrix, coords, radii, chunk_size, smooth_window, smooth_poly, verbose)
}

cpp_compute_delta_I_matrix_IND_fast <- function(expr_matrix, coords, radii, chunk_size = 1000L, smooth_window = 5L, smooth_poly = 2L, verbose = TRUE) {
    .Call(`_sigdiscov_cpp_compute_delta_I_matrix_IND_fast`, expr_matrix, coords, radii, chunk_size, smooth_window, smooth_poly, verbose)
}

cpp_compute_delta_I_matrix_directional <- function(expr_matrix, coords, radii, sender_percentile = 75.0, smooth_window = 5L, smooth_poly = 2L, verbose = TRUE) {
    .Call(`_sigdiscov_cpp_compute_delta_I_matrix_directional`, expr_matrix, coords, radii, sender_percentile, smooth_window, smooth_poly, verbose)
}

cpp_compute_signatures_multi_factor <- function(expr_matrix, gene_names, factor_indices, coords, radii, mode = 0L, sender_percentile = 75.0, smooth_window = 5L, smooth_poly = 2L, verbose = TRUE) {
    .Call(`_sigdiscov_cpp_compute_signatures_multi_factor`, expr_matrix, gene_names, factor_indices, coords, radii, mode, sender_percentile, smooth_window, smooth_poly, verbose)
}

